### ISSUE TITLE
Additional field for physical location in the Turnouts Tab WebUI

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/ESP32CommandStation#101]
I flipped to the tab just now and looking at the turnout list realized that what's missing is their locations - something that would describe each turnout's place on the layout.

Question is whether it would be possible to query the description from the Node's EventID entered, so it is auto-populated if available, otherwise even a simple text field would be better than nothing.

I don't know how we are doing for local storage, so this description doesn't need to be 255 characters either.

**Comment by atanisoft** [comment]
Adding a "name" or "location name" field should be doable. Having the CS probe the OpenLCB Event ID description may be possible but it would be a considerable amount of work in a generic manner.
