### ISSUE TITLE
Add support for pre-defined routes

### ISSUE THREAD

**Issue by atanisoft** [atanisoft/ESP32CommandStation#106]
Currently it is only possible to define turnouts but not routes which consist of multiple turnouts, either DCC or OpenLCB based turnouts.

**Comment by TrainzLuvr** [comment]
We can already chain LCC events - isn't that creating routes, or do you have something else in mind?

**Comment by atanisoft** [comment]
This will be more for the DCC side than just OpenLCB event chaining.
