### ISSUE TITLE
There are some problems with WiFi and Display at compile time

### ISSUE THREAD

**Issue by murarduino** [atanisoft/ESP32CommandStation#120]
1. I want to use STA mode so that other devices in my home can access ESP32CS .
WiFi Mode ->Connect to SSID
Station Configuration is my home Wifi information 
Hostname prefix ->esp32cs_mura

2. I have a SH1106 OLED, 128*64. Status is configured as follows:
Display Type->OLED 
Display  Size  ->128*64 
Font -> Bold 
Vertically flip display ->Null 
Contrast  Level ->128

The compiler reported the following error:

D:\esp\ESP32CommandStation>idf.py build
Executing action: all (aliases: build)
Running ninja in directory d:\esp\esp32commandstation\build
Executing "ninja all"...
[0/1] Re-running CMake...
-- ccache will be used for faster recompilation
-- Building ESP-IDF components for target esp32
Processing 2 dependencies:
[1/2] OpenMRNIDF (a91fe3f613cb2e0ef97764d41997fc33f4e09cc5)
[2/2] idf (4.4.4)
-- DEBUG: Use esp-modbus component folder: D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/freemodbus.
-- Project sdkconfig file D:/esp/ESP32CommandStation/sdkconfig
Loading defaults file D:/esp/ESP32CommandStation/sdkconfig.defaults...
D:/esp/ESP32CommandStation/sdkconfig.defaults:36 CONFIG_ULP_COPROC_ENABLED was replaced with CONFIG_ESP32_ULP_COPROC_ENABLED
-- App "ESP32CommandStation" version: v2.0.0-beta1-5-g14cf760-dirty
-- Adding linker script D:/esp/ESP32CommandStation/build/esp-idf/esp_system/ld/memory.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_system/ld/esp32/sections.ld.in
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.api.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.newlib-data.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.syscalls.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.newlib-time.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/soc/esp32/ld/esp32.peripherals.ld
-- Adding linker script D:/esp/ESP32CommandStation/build/esp-idf/ULPADC/ulp_adc_ops/ulp_adc_ops.ld
-- Automatic configuration of OPS and PROG using L298
-- Components: AccessoryDecoderDB Config DCC HttpServer NeoPixelBus NvsManager OpenMRNExtensions OpenMRNIDF StatusDisplay StatusLED TrainDatabase TrainManager ULPADC Utils app_trace app_update bootloader bootloader_support cbor console cxx driver efuse esp32 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hw_support esp_ipc esp_netif esp_phy esp_pm esp_ringbuf esp_rom esp_system esp_timer esp_wifi espcoredump esptool_py expat fatfs freertos hal heap ieee802154 jsmn json libsodium log lwip main mbedtls mdns newlib nvs_flash openssl openthread partition_table pthread sdmmc soc spi_flash spiffs tcpip_adapter ulp usb vfs wear_levelling wpa_supplicant xtensa
-- Component paths: D:/esp/ESP32CommandStation/components/AccessoryDecoderDB D:/esp/ESP32CommandStation/components/Config D:/esp/ESP32CommandStation/components/DCC D:/esp/ESP32CommandStation/components/HttpServer D:/esp/ESP32CommandStation/components/NeoPixelBus D:/esp/ESP32CommandStation/components/NvsManager D:/esp/ESP32CommandStation/components/OpenMRNExtensions D:/esp/ESP32CommandStation/managed_components/OpenMRNIDF D:/esp/ESP32CommandStation/components/StatusDisplay D:/esp/ESP32CommandStation/components/StatusLED D:/esp/ESP32CommandStation/components/TrainDatabase D:/esp/ESP32CommandStation/components/TrainManager D:/esp/ESP32CommandStation/components/ULPADC D:/esp/ESP32CommandStation/components/Utils D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/app_trace D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/app_update D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader_support D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/cbor D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/console D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/cxx D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/driver D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/efuse D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp32 D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_adc_cal D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_common D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_eth D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_event D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_gdbstub D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_hw_support D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_ipc D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_netif D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_phy D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_pm D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_ringbuf D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_system D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_timer D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_wifi D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/espcoredump D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esptool_py D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/expat D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/fatfs D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/freertos D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/hal D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/heap D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/ieee802154 D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/jsmn D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/json D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/libsodium D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/log D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/lwip D:/esp/ESP32CommandStation/main D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/mbedtls D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/mdns D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/newlib D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/nvs_flash D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/openssl D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/openthread D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/partition_table D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/pthread D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/sdmmc D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/soc D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/spi_flash D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/spiffs D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/tcpip_adapter D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/ulp D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/usb D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/vfs D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/wear_levelling D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/wpa_supplicant D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/xtensa
-- SNIP: ESP32CommandStation/atanisoft.github.io/v2.0.0-beta1-5-g14cf/1.0.0
../web/index.html
../web/cash.min.js
../web/spectre.min.css
../web/cdi.js
-- Configuring done
-- Generating done
-- Build files have been written to: D:/esp/ESP32CommandStation/build
[2/61] Performing configure step for 'ulp_adc_ops'
-- Building ULP app ulp_adc_ops for esp32
-- ULP assembler version: 2.35_20220830
-- Configuring done
-- Generating done
-- Build files have been written to: D:/esp/ESP32CommandStation/build/esp-idf/ULPADC/ulp_adc_ops
[3/61] Generating ../../partition_table/partition-table.bin
Partition table binary generated. Contents:
*******************************************************************************
# ESP-IDF Partition Table
# Name, Type, SubType, Offset, Size, Flags
nvs,data,nvs,0x9000,20K,
otadata,data,ota,0xe000,8K,
ota_0,app,ota_0,0x10000,1728K,
ota_1,app,ota_1,0x1c0000,1728K,
coredump,data,coredump,0x370000,64K,
spiffs,data,spiffs,0x380000,512K,
*******************************************************************************
[4/61] Performing build step for 'ulp_adc_ops'
[1/1] Generating ulp_adc_ops.ld, ulp_adc_ops.h
[28/60] Building CXX object esp-idf/StatusDisplay/CMakeFiles/__idf_StatusDisplay.dir/StatusDisplay.cpp.obj
FAILED: esp-idf/StatusDisplay/CMakeFiles/__idf_StatusDisplay.dir/StatusDisplay.cpp.obj
ccache D:\esp\Espressif\tools\xtensa-esp32-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-g++.exe -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -ID:/esp/ESP32CommandStation/build/config -ID:/esp/ESP32CommandStation/components/StatusDisplay/include -ID:/esp/ESP32CommandStation/components/StatusDisplay/private_include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/newlib/platform_include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/freertos/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/freertos/include/esp_additions/freertos -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/freertos/port/xtensa/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/freertos/include/esp_additions -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_hw_support/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_hw_support/include/soc -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_hw_support/include/soc/esp32 -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_hw_support/port/esp32/. -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_hw_support/port/esp32/private_include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/heap/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/log/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/lwip/include/apps -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/lwip/include/apps/sntp -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/lwip/lwip/src/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/lwip/port/esp32/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/lwip/port/esp32/include/arch -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/soc/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/soc/esp32/. -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/soc/esp32/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/hal/esp32/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/hal/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/hal/platform_port/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/include/esp32 -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32 -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_common/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_system/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_system/port/soc -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_system/port/public_compat -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp32/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/xtensa/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/xtensa/esp32/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/driver/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/driver/esp32/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_pm/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_ringbuf/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/efuse/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/efuse/esp32/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/vfs/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_wifi/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_event/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_netif/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_eth/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/tcpip_adapter/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_phy/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_phy/esp32/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_ipc/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/app_trace/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_timer/include -ID:/esp/ESP32CommandStation/components/Config/include -ID:/esp/ESP32CommandStation/managed_components/OpenMRNIDF/src -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/app_update/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/spi_flash/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader_support/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/mdns/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/console -ID:/esp/ESP32CommandStation/components/NvsManager/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/nvs_flash/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/mbedtls/port/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/mbedtls/mbedtls/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/mbedtls/esp_crt_bundle/include -ID:/esp/ESP32CommandStation/components/OpenMRNExtensions/src -ID:/esp/ESP32CommandStation/components/Utils/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/fatfs/diskio -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/fatfs/vfs -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/fatfs/src -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/wear_levelling/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/sdmmc/include -ID:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/spiffs/include -ID:/esp/ESP32CommandStation/components/StatusLED/include -ID:/esp/ESP32CommandStation/components/NeoPixelBus/src -ID:/esp/ESP32CommandStation/components/HttpServer/include -mlongcalls -Wno-frame-address  -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fstack-protector -fmacro-prefix-map=D:/esp/ESP32CommandStation=. -fmacro-prefix-map=D:/esp/Espressif/frameworks/esp-idf-v4.4.4=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu++14 -D_GNU_SOURCE -DIDF_VER=\"v4.4.4-dirty\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -D_GLIBCXX_USE_C99 -Wno-ignored-qualifiers -Wno-implicit-fallthrough -DSNIP_PROJECT_PAGE=\"atanisoft.github.io\" -DSNIP_HW_VERSION=\"1.0.0\" -DSNIP_SW_VERSION=\"v2.0.0-beta1-5-g14cf\" -DSNIP_PROJECT_NAME=\"ESP32CommandStation\" -DCDI_VERSION=0x0200 -DESP32 -MD -MT esp-idf/StatusDisplay/CMakeFiles/__idf_StatusDisplay.dir/StatusDisplay.cpp.obj -MF esp-idf\StatusDisplay\CMakeFiles\__idf_StatusDisplay.dir\StatusDisplay.cpp.obj.d -o esp-idf/StatusDisplay/CMakeFiles/__idf_StatusDisplay.dir/StatusDisplay.cpp.obj -c D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp: In lambda function:
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp:129:28: error: 'ipv4_to_string' was not declared in this scope
             wifi("IP: %s", ipv4_to_string(ip).c_str());
                            ^~~~~~~~~~~~~~
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp: In member function 'StateFlowBase::Action esp32cs::StatusDisplay::init()':
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp:198:29: error: 'int64_to_string_hex' was not declared in this scope
       scanresults += "\n" + int64_to_string_hex(addr) + ":";
                             ^~~~~~~~~~~~~~~~~~~
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp:208:22: error: 'int64_to_string_hex' was not declared in this scope
       scanresults += int64_to_string_hex(addr);
                      ^~~~~~~~~~~~~~~~~~~
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp: In member function 'StateFlowBase::Action esp32cs::StatusDisplay::update()':
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp:256:19: error: 'trainmgr' was not declared in this scope
         Singleton<trainmgr::LocoManager>::instance()->active_locos();
                   ^~~~~~~~
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp:256:19: note: suggested alternative: '_raise_r'
         Singleton<trainmgr::LocoManager>::instance()->active_locos();
                   ^~~~~~~~
                   _raise_r
D:/esp/ESP32CommandStation/components/StatusDisplay/StatusDisplay.cpp:256:40: error: template argument 1 is invalid
         Singleton<trainmgr::LocoManager>::instance()->active_locos();
                                        ^
[37/60] Performing configure step for 'bootloader'
-- Building ESP-IDF components for target esp32
-- DEBUG: Use esp-modbus component folder: D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/freemodbus.
-- Project sdkconfig file D:/esp/ESP32CommandStation/sdkconfig
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/soc/esp32/ld/esp32.peripherals.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.api.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.libgcc.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom/esp32/ld/esp32.rom.newlib-funcs.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader/subproject/main/ld/esp32/bootloader.ld
-- Adding linker script D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader/subproject/main/ld/esp32/bootloader.rom.ld
-- Components: bootloader bootloader_support efuse esp32 esp_common esp_hw_support esp_rom esp_system esptool_py freertos hal log main micro-ecc newlib partition_table soc spi_flash xtensa
-- Component paths: D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader_support D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/efuse D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp32 D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_common D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_hw_support D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_rom D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esp_system D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/esptool_py D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/freertos D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/hal D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/log D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader/subproject/main D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/bootloader/subproject/components/micro-ecc D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/newlib D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/partition_table D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/soc D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/spi_flash D:/esp/Espressif/frameworks/esp-idf-v4.4.4/components/xtensa
-- Configuring done
-- Generating done
-- Build files have been written to: D:/esp/ESP32CommandStation/build/bootloader
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by atanisoft** [comment]
This looks loosely related to https://github.com/atanisoft/ESP32CommandStation/issues/119. Those functions should be declared in OpenMNRIDF and through a few components, it may be a missing include. I'll take a look.
