### ISSUE TITLE
Wi-Fi missing BTS7960B wiring and capabilities

### ISSUE THREAD

**Issue by jrob3rts** [atanisoft/ESP32CommandStation#16]
Hi,

I've been following this since the last update I posted to the Halted screen.  Due to work etc, I never finished the build for my son however I am keen to finish this soon.

I believe the IBT_2 Will handle a greater currently than the standard shield so keen to give that a go but I'm lost without some kind of help connecting this to the ESP32.

Any help would be great.

**Comment by jrob3rts** [comment]
P.S.  looking forward to v1.2 :)

**Comment by atanisoft** [comment]
Connections have been documented on the development branch with planned merge to master this coming weekend.
