### ISSUE TITLE
Reconfigure wifi

### ISSUE THREAD

**Issue by jpnarkinsky** [atanisoft/ESP32CommandStation#40]
Hi there, I'm trying to get this built and running for the first time.  I configured the wrong wifi SSN (the 5.8 ghz one instead of the 2.4 ghz one) and flashed it to my device.  I figure this out quickly, and I've reconfigured it, but it continues to try to connect the 5.8 ghz SSN.  That is, the changes to the wifi configuration don't seem to be taking effect.  I've done a `idf.py fullclean`, etc., but nothing seems to be taking effect.

Any suggestions?  I'm brand new to ESP32, so it's certainly possible I'm doing it wrong.  Thanks for any suggestions!

**Comment by atanisoft** [comment]
Run: `idf.py erase_flash` and then `idf.py flash monitor`.

**Comment by atanisoft** [comment]
Another option is enable the factory reset pin via config and flash that with the pin held low. It should force clear settings and reconfigure based on the values you enter in the config.

**Comment by jpnarkinsky** [comment]
Thanks!  That did it.
