### ISSUE TITLE
DCC Signal->OPS->Railcom UART selection is ambiguous

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/ESP32CommandStation#44]
When enabling Railcom, an option is presented to select a Railcom UART: UART1 or UART2.

This is rather ambiguous because UART1 is already reserved to provide optional output on pins 5 and 16 via J3, as per the current ESP32CS schematic.

I believe there should not be an option to select UART (or default to UART2), unless UART1 could be shared somehow between Railcom and the UART1 header J3.

**Comment by atanisoft** [comment]
This is one downside of the current `idf.py menuconfig` utility, there is no clear way to declare a set of [defaults](https://github.com/atanisoft/ESP32CommandStation/blob/master/sdkconfig.defaults) and [target](https://github.com/atanisoft/ESP32CommandStation/blob/master/sdkconfig.defaults.pcb) specific overlays. In the CI build I work around this limitation [here](https://github.com/atanisoft/ESP32CommandStation/blob/master/.github/build.sh#L50-L66) by adding the extra defaults file, but I have not found a way to automate this via `idf.py menuconfig` or within VSCode via the extension.
