### ISSUE TITLE
Changing an IP address (and possibly other parameters) of WiFi config should not require a full rebuild

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/ESP32CommandStation#46]
Since I am not using the CS as a AP, it connects to my existing WiFi network.

Using _idf.py menuconfig_ I add a static IP address along with my SSID/password parameters.

_idf.py build_ does an entire build all over again, which I believe should not be necessary.

I did not try to see whether changing SSID or password or any other parameter also did a full rebuild, but I presume it does.

**Comment by atanisoft** [comment]
Changes done inside menuconfig rebuilds the sdkconfig file which results in a full rebuild. That is one downside to the current build mechanism esp-idf uses.

You can also configure all wifi settings via the web interface as well.
