### ISSUE TITLE
Turning CAN interface in WebUI does not stick

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/ESP32CommandStation#47]
Trying to turn the CAN interface On using a WebUI does not result in button sticking - upon restart/refresh the button is still toggled Off.

**Comment by atanisoft** [comment]
@TrainzLuvr After toggling the CAN on/off, did you click save?

**Comment by TrainzLuvr** [comment]
Of course, several times I tried this and upon going back to LCC tab, the option is still toggled off.

EDIT: to add, this happens whether I do it with a mobile, or desktop browser.
