### ISSUE TITLE
"The command station reported a failure retrieving configuration data"

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/ESP32CommandStation#59]
Unable to save settings from web UI.

![https://i.ibb.co/QP59VxK/Capture.jpg](https://i.ibb.co/QP59VxK/Capture.jpg)

**Comment by atanisoft** [comment]
Fixed in https://github.com/atanisoft/ESP32CommandStation/commit/cb479561203c6ab861df5514145d863a363419c3
