### ISSUE TITLE
Update the README.md for better grasp

### ISSUE THREAD

**Issue by keivalya** [atanisoft/ESP32CommandStation#70]
I notice the README.md is not the best that it could potentially be. I can be more elaborative and easy to read for even beginners.
It can also be made more visually attractive.

**Comment by keivalya** [comment]
I'g like to help in doing so.

**Comment by atanisoft** [comment]
@keivalya I'm not sure I understand what you are intending. The README.md file is intentionally brief as the documentation is on the website instead.  But feel free to submit a PR with your updates and I'll take a look

**Comment by keivalya** [comment]
Definitely!

**Comment by atanisoft** [comment]
@keivalya Any progress on a PR?

**Comment by keivalya** [comment]
No @atanisoft 
I think you were right. README is already enough elaborative for a beginner.

You may close this issue. I won't be able to work on it even if I could, due to my exams.
Sorry for the trouble. I should have followed up.

**Comment by atanisoft** [comment]
@keivalya No worries, life can be very busy at times. Best of luck in your exams!

**Comment by keivalya** [comment]
Thank you so much for understanding @atanisoft 😄
