### ISSUE TITLE
E-STOP from the throttle does not work

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/ESP32CommandStation#86]
When using a UWT-100 via WiFi (LCC mode) and issuing either an E-STOP ALL LOCOS, or E-STOP LAYOUT OFF, the CS does not register the event. Neither does it register the release of the above mentioned events.

The serial monitor does not log anything, and I would expect to at least see OPS Off or something of that kind, and the same for All Locos.

**Comment by atanisoft** [comment]
It sounds like the event didn't arrive or was not recognized. It should have printed something to the screen for sure. Will check
