### ISSUE TITLE
WebUI: Locomotive Direction toggle event is reversed

### ISSUE THREAD

**Issue by TrainzLuvr** [atanisoft/ESP32CommandStation#87]
In the WebUI, the Locomotive Direction toggle button defaults to FWD, yet the serial monitor registers FWD event when the button is toggled to REV, and then REV event when the button is toggled back to FWD.

```
[DCC++ loco 5903] Set direction to FWD
[DCC++ loco 5903] Set direction to REV
```

**Comment by atanisoft** [comment]
Interesting, haven't seen this and thought it was fixed a while ago. Will check.
