### ISSUE TITLE
Make failed on Windows

### ISSUE THREAD

**Issue by nmeunier** [atanisoft/ESP32CommandStation#98]
**OS**: Windows 10
**Branch**: master

When the command "idf.py menuconfig" is launched, the make failed and return the following error :

```
CMake Error at CMakeLists.txt:65 (message):
  Unable to find 'gzip' program

-- Configuring incomplete, errors occurred!
cmake failed with exit code 1
```

The gzip tool is not available on Windows

**Comment by atanisoft** [comment]
gzip is available for windows but is not available unless you install it.. http://gnuwin32.sourceforge.net/packages/gzip.htm. Note that the CMake build will look for it in "\bin" on the drive which has the code on it.
